# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  executor:
    name: node/default

orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test

  test:
    <<: *defaults
    steps:
      - run: yarn test

workflows:
  deploy:
    jobs:
      - build
      - test:
          requires:
            - build
