# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/platr
  docker:
    - image: circleci/node:10.15.1


restore: &restore
  restore_cache:
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}


save: &save
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - *restore

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - *save

      - persist_to_workspace:
          root: ~/platr
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/platr

      - run:
          name: Run tests
          command: yarn lint

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/platr

      - add_ssh_keys:
          fingerprints:
            - "fa:6a:b2:26:6e:f4:0a:9a:71:15:18:76:36:d1:66:a3"

      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/platr/.npmrc

      - run:
          name: Publish packages
          command: npx lerna publish

      - *save

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /feature\/*/
                - master

      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - /feature\/*/
                - master

      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
