# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release and publish NPM packages

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup NodeJS"
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
          registry-url: https://registry.npmjs.org/

      - name: Authenticate with Registry
        run: |
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Run code linting"
        run: yarn run lint

      - name: "Run tests"
        run: yarn run test

      - name: "Create version and publish NPM packages"
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
